#!/usr/bin/env node
// Munin plugin for CouchDB database io

// Magic Markers for auto-configuration
// #%# family=auto
// #%# capabilities=autoconf suggest

var sys = require("sys")
  , exec = require("child_process").exec
  , mode = "fetch"

// could be "config" or "autoconf" mode
if (process.argv[2] !== undefined) mode = process.argv[2]

exec("cat /proc/stat |egrep '^cpu[0-9]+'|wc -l", function(err, ncpu) {
  ncpu = parseInt(ncpu)
  var percent = ncpu * 100
    , maximum = percent
    , limit = percent

  if (mode === 'config') {
    sys.puts("graph_title CouchDB CPU usage")
    sys.puts("graph_args --base 1000 -r --lower-limit 0 --upper-limit " + limit)
    sys.puts("graph_category couchdb")
    sys.puts("cpu.label cpu")
    sys.puts('cpu.draw AREA')
    sys.puts("cpu.max " + maximum)
    sys.puts('cpu.min 0')
    sys.puts('cpu.type DERIVE')
  } else {
    var cpu = 0
    exec("ps -U couchdb -u couchdb u", function(err, data) {
      data = data.split("\n")
      data.shift()
      data.pop()

      data.forEach(function(line) {
        var values = line.split(/\s+/)
        cpu += parseFloat(values[2])
      })

      sys.puts("cpu.value " + cpu)
    })
  }
})

