#!/usr/bin/env node
// Munin plugin for CouchDB database disk sizes

// Magic Markers for auto-configuration
// #%# family=auto
// #%# capabilities=autoconf suggest

var http = require("http")
  , sys = require("sys")

var client = http.createClient(5984, "localhost")
var req = client.request('GET', '/_all_dbs')

req.on('response', function(res) {
    if (process.argv[2] !== undefined && process.argv[2] == 'autoconf') {
        if (res.statusCode === 200) {
            sys.puts("yes")
        } else {
            sys.puts("no")
            process.exit(1)
        }
    } else {
        var body = ''
        res.on('data', function(chunk) {
            body += chunk
        })
        res.on('end', function() {
            var dbs = JSON.parse(body)

            if (process.argv[2] !== undefined && process.argv[2] == 'config') {
                sys.puts("graph_title CouchDB db disk sizes");
                sys.puts("graph_args --base 1048576");
                sys.puts("graph_vlabel Disk sizes in Megabytes");
                sys.puts("graph_category couchdb");
            }

            dbs.forEach(function(db) {
                if (process.argv[2] !== undefined && process.argv[2] == 'config') {
                    sys.puts(db + "_disk_size.label " + db);
                    sys.puts(db + "_disk_size.type COUNTER");
                    sys.puts(db + "_disk_size.min 0");
                    sys.puts(db + "_disk_size.max 1000000");
                } else {
                    var db_req = client.request('GET', '/' + db)
                    db_req.on('response', function(res) {
                        var body = ''
                        res.on('data', function(chunk) {
                            body += chunk
                        })
                        res.on('end', function() {
                            var stat = JSON.parse(body)
                            sys.puts(db + "_disk_size.value " + stat.disk_size)
                        })
                    })
                    db_req.end()
                }
            })
        })
    }
})

req.end()

